export const jokes: string[] = [
  'Was macht ein Keks unter einem Baum? Krümel.',
  'Wie nennt man einen Boomerang, der nicht zurückkommt? Einen Stock.',
  'Warum können Geister so schlecht lügen? Man sieht durch sie hindurch.',
  'Was ist grün und steht vor der Tür? Ein Klopfsalat.',
  'Warum weinen Bienen? Weil ihre Mutter Wespe ist.',
  'Was sitzt auf einer Tanne und ärgert sich? Ein Kuckuck, der keine Uhr findet.',
  'Wie nennt man einen Bumerang, der zurückkommt, obwohl man ihn nicht geworfen hat? Stock.',
  'Was ist orange und läuft durch den Wald? Eine Wanderine.',
  'Zwei Kekse fallen in eine Fritteuse. Sagt der eine: „Heiß hier, oder?"',
  'Was ist braun, klebrig und läuft durch die Wüste? Ein Karamel.',
  'Wie nennt man einen Pinguin in der Wüste? Verirrt.',
  'Was sagt eine Kuh, wenn sie schweigt? Nichts, Muuh.',
  'Warum tragen Fische keine Wasserstoffbomben? Zu schwer.',
  'Was ist weiß und stört beim Skifahren? Eine Lawine.',
  'Wie heißt der Nachbar von Herrn Igel? Herr Nachbarhecke.',
  'Treffen sich zwei Jäger. Beide tot.',
  'Was macht ein Clown im Büro? Faxen.',
  'Wie nennt man einen dicken Vegetarier? Biotonne.',
  'Was ist gelb und kann nicht schwimmen? Ein Bagger.',
  'Kommt ein Pferd in die Bar. Fragt der Barkeeper: „Warum so ein langes Gesicht?"',
  'Warum gehen Skelette nicht gerne auf Partys? Sie haben keinen Körper zum Tanzen.',
  'Was sagt der Elektriker zu seiner Frau? Ich liebe dich unendlich, aber lass uns kurz erden.',
  'Was ist rot und schlecht für die Zähne? Ein Backstein.',
  'Wie nennt man einen Bauern ohne Traktor? Zu Fuß gehend, denke ich.',
  'Warum können Frösche jederzeit sterben? Sie kroaken einfach ab.',
  'Was liegt auf dem Meeresgrund und zittert? Ein Nervenwrack.',
  'Wie heißt der beste Tänzer unter den Fischen? Michael Flunder.',
  'Was ist klein, grün und lässt sich nicht verjagen? Eine hartnäckige Erbse.',
  'Warum ging der Mathematiker nicht in den Wald? Zu viele Wurzeln.',
  'Was sagt ein Buchstabe zum anderen? Wir sehen uns im Alphabet.',
  'Wie nennt man einen Kaktus in der Wüste? Unauffällig.',
  'Was ist grau, hat vier Beine und einen Rüssel? Eine Maus auf Dienstreise nach Afrika.',
  'Warum hat der Bäcker keine Zeit? Er hat alle Hände voll Teig.',
  'Was sagt ein Vulkan zum anderen? Ich hab dich zum Fressen gern.',
  'Wie nennt man ein Croissant in Frankreich? Ganz normal.',
  'Was ist schwarz-weiß und liest gern Zeitung? Ein Zebra in der U-Bahn.',
  'Warum sind Kalender so beliebt? Sie haben immer ein Datum.',
  'Was ist der Unterschied zwischen einem Fisch und einem Klavier? Man kann keinen Fisch stimmen.',
  'Wie nennt man einen Bumerang, der nicht funktioniert? Einen sehr geraden Stock.',
  'Was sagt der Blinddarm zum Gehirn? Wart mal, ich hab da noch was im Sinn.',
];
